apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
- deployment.yaml
- route.yaml
- service.yaml
images:
- name: quay.io/upslopeio/eurotunnel-app
  newName: quay.io/theorei/eurotunnel-app
  newTag: 8aff3781cc5c43e6ac137b2d827af16bca4ce0a1ee7419e35d71b5f8da6a82e3
commonLabels:
  app.kubernetes.io/instance: eurotunnel-app
  app.kubernetes.io/name: eurotunnel-app
