apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: eurotunnel-app
spec:
  workspaces: 
    - name: pipeline-shared-data
  params:
    - name: github-repo
      type: string
      description: GitHub repository url
    - name: image-repo
      type: string
      description: Docker image repository
    - name: app-name
      type: string
      description: Application name
  
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      params: 
        - name: url
          value: $(params.github-repo)
      workspaces:
        - name: output
          workspace: pipeline-shared-data

    - name: run-tests
      params:
      - name: ARGS
        value:
        - install-ci-test
      runAfter:
      - fetch-repository
      taskRef:
        name: npm
        kind: Task
      workspaces:
      - name: source
        workspace: pipeline-shared-data

    - name: create-image
      params:
      - name: IMAGE
        value: "$(params.image-repo):$(tasks.fetch-repository.results.commit)"
      runAfter:
      - run-tests
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
      - name: source
        workspace: pipeline-shared-data

    - name: create-configuration
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: source-repo
          value: "$(params.github-repo)"
        - name: commit
          value: "$(tasks.fetch-repository.results.commit)"
        - name: image-repo
          value: "$(params.image-repo)"
      runAfter:
        - create-image
      taskRef:
        name: create-configuration
      workspaces:
        - name: source
          workspace: pipeline-shared-data

    - name: deploy
      params:
        - name: manifest
          value: "$(tasks.create-configuration.results.manifest)"
        - name: app-namespace
          value: "$(context.pipelineRun.namespace)"
      runAfter:
        - create-configuration
      taskRef:
        name: deploy
      workspaces:
        - name: source
          workspace: pipeline-shared-data